### ISSUE TITLE
Is that possible to make it compatible with current game version?

### ISSUE THREAD

**Issue by fafaraway** [Oldsalt0/SpellReplay#1]
Love this addon, it's really better than trufigcd, could you make it compatible with current game version(BfA 8.0)?

**Comment by Oldsalt0** [comment]
Hello, thanks for the feedback! I'm away until the end of May but after that I can sure try to make it work with current game version
Send me a PM on Discord (Oldsalt#8265)

**Comment by wang602291008** [comment]
Poisons applied (or resisted) on Shiv。。。     Why don't i show it here ？  
Does it have this function ？

**Comment by Oldsalt0** [comment]
@wang602291008 Sorry for the late answer but no, the addon did not have the function.
@neotpravlennoye If you're still playing the game, I'm a bit late on that but Anonaut forked and made the addon work for TBCC. So it should work much better in current game versions : https://github.com/anonaut/SpellReplay
